### ISSUE TITLE
Many of the Keymaps aren't loading on OS X

### ISSUE THREAD

**Issue by jimklo** [mgaitan/sublime-rst-completion#82]
Installed a fresh copy of ST3 on new machine with Yosemite.  
Installed Package Control and sublime-rst-completion.
I've tried installing both the PC version and source via GitHub.

Many of the key bindings (super+shift+t, super+shift+b, etc)

I notice that in the console that after trying what should be this packages key binding:

```
no command for selector: noop:
```

Not even sure what is wrong or going on.

super+shift+r seems to be the only binding that I can find that works.

**Comment by mgaitan** [comment]
hey @jimklo, I'm just updated st3 to the last stable build (3083) and I can't reproduce the bug. I'm on ubuntu, so, this seems to be a mac only bug. Could you help me to debug it a bit more?

**Comment by jimklo** [comment]
@mgaitan sure... Unfortunately I'm somewhat floundering at ST3 development - I'm not exactly 100% sure on how to debug it further.  ST3 also seems to keep all the plug-ins packed; complicating some things as well (i.e. none of the "default" settings are accessible via the Package Control version)

I've tried wiping out the keybindings all together and trying a limited set.  They seem to not be getting picked up. Not quite sure how to debug this.

**Comment by mgaitan** [comment]
in first place, thanks! 

in ST3 the default packaging system is a zip file, with the extension `.sublime-package`. However you can still can still override the content of any existent package, putting your modified files in a directory with the same name. 

> Loose packages may be stored in:
>
>    `<data_path>/Packages`

> For example, the package Python is stored in `<executable_path>/Packages/Python.sublime-package`, and any files in the `<data_path>/Packages/Python` directory will override those stored in the `.sublime-package` file. 

https://www.sublimetext.com/docs/3/packages.html

The `<data_path>` folder in mac, seems to be  `~/Library/Application Support/Sublime Text 3`

Also, this tool may be useful https://github.com/skuroda/PackageResourceViewer

**Comment by jimklo** [comment]
Okay... I think I figured it out why it isn't working.  Not a bug but maybe of "feature" of how ST determines the "super" key.  Turns out this laptop, I think I have some odd setting that makes me use the "fn" key alone with the "command" key to get "super".
