### ISSUE TITLE
"Settings - Default" and "Keybindings - Defaults" are empty

### ISSUE THREAD

**Issue by yoonghm** [mgaitan/sublime-rst-completion#96]
The file "Settings - Default" and "Keybindings - Defaults" are empty.  When I try to save the file, it tries to save into
```
..\Data\Packages\sublime-rst-completion\sublime-rst-completion.sublime-settings
```

But the settings should be in
```
Data\Packages\User
```

**Comment by lon91ong** [comment]
menu "Preferences - Settings"，“ignored_packages" annotate the reStructured Text
